# Default initial positions for right_arm's ros2_control fake system

initial_positions:
  arm_right_1_joint: 0
  arm_right_2_joint: 0
  arm_right_3_joint: 0
  arm_right_4_joint: 0
  arm_right_5_joint: 0
  arm_right_6_joint: 0
  arm_right_7_joint: 0